version: '3.7'

name: aggr-ui

services:
  front:
    container_name: aggr-ui-prod
    image: aggr-ui-prod
    build:
      context: ../.
      dockerfile: ./docker/Dockerfile
      args:
        - WORKDIR='/app'
    ports:
      - 8080:80
    env_file:
      - ../.env
      - ../.env.production
    restart: always
